services:
  apisix:
    image: apache/apisix:latest
    ports:
      - "9080:9080"  # Porta para o gateway
      - "9180:9180"  # Porta para o painel de controle
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:latest
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
